# Generated by Django 3.2.15 on 2022-09-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockexchange',
            options={'verbose_name_plural': 'Stock Exchanges'},
        ),
        migrations.AddField(
            model_name='stock',
            name='logo',
            field=models.ImageField(blank=True, upload_to='stock_logos/'),
        ),
        migrations.AlterField(
            model_name='stockexchange',
            name='name',
            field=models.CharField(choices=[('NYSE', 'New York Stock Exchange'), ('NASDAQ', 'NASDAQ'), ('TSX', 'Toronto Stock Exchange'), ('LSE', 'London Stock Exchange'), ('FWB', 'Frankfurt Stock Exchange')], max_length=100),
        ),
    ]
