# Generated by Django 3.2.15 on 2022-09-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220927_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='logo',
            field=models.ImageField(blank=True, upload_to='stock_logos'),
        ),
    ]
