# Generated by Django 4.1.1 on 2022-10-01 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_alter_stockprice_options_alter_stockprice_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockprice',
            options={'ordering': ['-datetime_created', 'stock'], 'verbose_name_plural': 'Stock Prices'},
        ),
        migrations.CreateModel(
            name='StockOrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('price_executed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
