# Generated by Django 3.2.15 on 2022-09-29 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocksowned',
            options={'verbose_name_plural': 'Stocks Owned'},
        ),
    ]
